@echo off
setlocal EnableExtensions

REM Livedoc2 Launcher
REM Generated by project-menu skill. Customize freely.

pushd "%~dp0" >nul

REM Prefer pwsh (PowerShell 7+) for better terminal support.
where pwsh >nul 2>&1
if %errorlevel% equ 0 (
    pwsh -NoProfile -ExecutionPolicy Bypass -File "%~dp0livedoc2.ps1" %*
) else (
    powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0livedoc2.ps1" %*
)
set "exitCode=%errorlevel%"

popd >nul
endlocal & exit /b %exitCode%

